export const ESTADOS_DOCS = ["EN PROCESO", "NOVEDAD", "RECHAZADO", "SOLUCIONADO"];

export const ALL_FIELDS_DOCS = [
  { key: "nombreEmisor", label: "Proveedor", w: 180, type: "text" },
  { key: "nitEmisor", label: "NIT", w: 110, type: "text" },
  { key: "estado", label: "Estado", w: 130, editable: "compras", type: "select" },
  { key: "tipoDocumento", label: "Tipo", w: 70, type: "text" },
  { key: "numeroDocumento", label: "# Factura", w: 100, type: "text" },
  { key: "ordenCompra", label: "# Orden Compra", w: 120, editable: "compras", type: "text" },
  { key: "rp", label: "# RP", w: 80, editable: "compras", type: "text" },
  { key: "fechaEmision", label: "Fecha Factura", w: 100, type: "text" },
  { key: "valorTotal", label: "Monto Facturado", w: 120, numeric: true, type: "text" },
  { key: "iva", label: "IVA", w: 90, numeric: true, type: "text" },
  { key: "centroCostos", label: "Centro Costos", w: 130, editable: "compras", type: "text" },
  { key: "departamento", label: "Departamento", w: 130, editable: "compras", type: "text" },
  { key: "fechaRecepcion", label: "F. Recepción", w: 100, type: "text" },
];

export const SAMPLE_DOCUMENTOS = [
  {
    id: "sample1",
    nitEmisor: "830144288",
    nombreEmisor: "DISTRIBRONCES SECO S.A.",
    tipoDocumento: "FE",
    numeroDocumento: "122346",
    fechaEmision: "16-09-2026",
    fechaRecepcion: "16-09-2026",
    emailRemitente: "ateb.facturacion@ateb.com.co",
    valorTotal: 5518482,
    iva: 881102,
    divisa: "COP",
    tieneXML: true,
    tienePDF: true,
    archivos: [{ nombre: "factura.xml", driveUrl: "#" }, { nombre: "representacion.pdf", driveUrl: "#" }],
    soportes: [],
    estado: "EN PROCESO",
    ordenCompra: "27533",
    rp: "",
    centroCostos: "",
    departamento: "",
    motivoRechazo: "",
    decidePor: "",
    fechaDecision: "",
  },
  {
    id: "sample2",
    nitEmisor: "901161429",
    nombreEmisor: "REPRESENTACIONES ELECTRICAS DE COLOMBIA SAS",
    tipoDocumento: "REC",
    numeroDocumento: "18134",
    fechaEmision: "16-09-2026",
    fechaRecepcion: "16-09-2026",
    emailRemitente: "facturacion@transaccionesco.siigo.net",
    valorTotal: 2989000,
    iva: 478240,
    divisa: "COP",
    tieneXML: true,
    tienePDF: false,
    archivos: [{ nombre: "factura.xml", driveUrl: "#" }],
    soportes: [],
    estado: "NOVEDAD",
    ordenCompra: "27414",
    rp: "",
    centroCostos: "obra Mirador de la...",
    departamento: "",
    motivoRechazo: "",
    decidePor: "",
    fechaDecision: "",
  },
  {
    id: "sample3",
    nitEmisor: "900025010",
    nombreEmisor: "INVERSIONES PRIM S.A.S",
    tipoDocumento: "FE",
    numeroDocumento: "405694",
    fechaEmision: "03-09-2026",
    fechaRecepcion: "03-09-2026",
    emailRemitente: "facturas@inversiones.com",
    valorTotal: 25577000,
    iva: 4092320,
    divisa: "COP",
    tieneXML: true,
    tienePDF: true,
    archivos: [{ nombre: "factura.xml", driveUrl: "#" }, { nombre: "soporte.pdf", driveUrl: "#" }],
    soportes: [{ nombre: "remision.pdf", driveUrl: "#" }],
    estado: "NOVEDAD",
    ordenCompra: "27378",
    rp: "37109",
    centroCostos: "Obra: BARU",
    departamento: "",
    motivoRechazo: "",
    decidePor: "",
    fechaDecision: "",
  },
  {
    id: "sample4",
    nitEmisor: "800231548",
    nombreEmisor: "FERRETERIA EL TORNILLO LTDA",
    tipoDocumento: "FE",
    numeroDocumento: "88213",
    fechaEmision: "10-09-2026",
    fechaRecepcion: "11-09-2026",
    emailRemitente: "facturacion@eltornillo.com.co",
    valorTotal: 1250000,
    iva: 200000,
    divisa: "COP",
    tieneXML: true,
    tienePDF: true,
    archivos: [{ nombre: "factura.xml", driveUrl: "#" }, { nombre: "factura.pdf", driveUrl: "#" }],
    soportes: [],
    estado: "RECHAZADO",
    ordenCompra: "27490",
    rp: "",
    centroCostos: "",
    departamento: "",
    motivoRechazo: "Orden de compra no coincide",
    decidePor: "Juan Perez",
    fechaDecision: "12-09-2026",
  },
  {
    id: "sample5",
    nitEmisor: "901022334",
    nombreEmisor: "SUMINISTROS INDUSTRIALES DEL NORTE S.A.S",
    tipoDocumento: "FE",
    numeroDocumento: "55021",
    fechaEmision: "05-09-2026",
    fechaRecepcion: "06-09-2026",
    emailRemitente: "cartera@sumindnorte.com",
    valorTotal: 8734500,
    iva: 1397520,
    divisa: "COP",
    tieneXML: true,
    tienePDF: true,
    archivos: [{ nombre: "factura.xml", driveUrl: "#" }, { nombre: "representacion.pdf", driveUrl: "#" }],
    soportes: [{ nombre: "acta_recibido.pdf", driveUrl: "#" }],
    estado: "SOLUCIONADO",
    ordenCompra: "27401",
    rp: "37088",
    centroCostos: "Obra: BARU",
    departamento: "Compras",
    motivoRechazo: "",
    decidePor: "",
    fechaDecision: "",
  },
];
